# introduction to python data types...
    # str = 'joy', "hello there"
    # int = 19, 1, 12224
    # float = 1.3, 34.5857843098
    # complex = 23j, 54j
    # list = ['joy', 56, 3.45464, 1j,['tuhin', 'joy']]
    # tuple = ('joy', 57, 4.34,['joy',57])
    # range = range(0, 13, 3) //1st number for range start, //2nd number for range end, //3rd number set range...
    # dict = {'name': 'joy', 'age': 23, 'family': [{'father': 'Jahangir', 'Mother': 'Monalisa'}]} //in dict have two type key and value..
    # set = {'Rohim', 'Korim', 'Joy', 'Shanto', 'Joy', 'Shanto'} //in set same data type cann't appliabal...
    # frozenset = (('joy', 100, 2.3, 3)) //in frozenset cann't apply duplicate value...
    # bool = True, False
    # bytes, bytearray, memoryview...
    # none //js in null python none...

# Arithmetic Operators...
    # +, -, *, /, %, **,//
    # PEMDAS
    # P = parenthesis ()
    # E = Exponent **
    # M = Multiplication *
    # D = Devition /
    # A = Addition +
    # S = Subtraction -
# Assignment Operators...
    #=, +=, -=, /=, %/, //=, **=
    # age = age + 2 or age += 2
#Logical Operators...
    # and, or, not
# Identity Operators...
    # is, is not
    